eureka-service:
  image: mateuszsojka/eureka-service
  container_name: eureka-service
  ports:
   - "8761:8761"

hystrix-dashboard:
  image: mateuszsojka/hystrix-dashboard
  container_name: hystrix-dashboard
  ports:
   - "7979:7979"
  links:
   - eureka-service

config-server:
  image: mateuszsojka/config-server
  container_name: config-server
  ports:
   - "8888:8888"
  links:
   - eureka-service

authservice:
  image: mateuszsojka/auth-service
  container_name: auth-service
  external_links:
   - usersdb:users_database
  links:
   - eureka-service
   - config-server

ebookservice:
  image: mateuszsojka/ebook-service
  container_name: ebook-service
  external_links:
  - ebookdb:ebook_database
  links:
   - eureka-service
   - config-server

imageservice:
  image: mateuszsojka/image-service
  container_name: image-service
  external_links:
  - imagedb:image_database
  links:
   - eureka-service
   - config-server

musicservice:
  image: mateuszsojka/music-service
  container_name: music-service
  external_links:
  - musicdb:music_database
  links:
   - eureka-service
   - config-server

videoservice:
  image: mateuszsojka/video-service
  container_name: video-service
  external_links:
  - videodb:video_database
  links:
   - eureka-service
   - config-server