discovery:
  image: mateuszsojka/eureka-service
  container_name: eureka-service
  ports:
   - "8761:8761"

hystrix:
  image: mateuszsojka/hystrix-dashboard
  container_name: hystrix-dashboard
  ports:
   - "7979:7979"
  links:
   - discovery

configserver:
  image: mateuszsojka/config-server
  container_name: config-server
  ports:
   - "8888:8888"
  links:
   - discovery

authservice:
  image: mateuszsojka/auth-service
  container_name: auth-service
  external_links:
   - usersdb:users_database
  links:
   - discovery
   - configserver

ebookservice:
  image: mateuszsojka/ebook-service
  container_name: ebook-service
  external_links:
  - ebookdb:ebook_database
  links:
   - discovery
   - configserver

imageservice:
  image: mateuszsojka/image-service
  container_name: image-service
  external_links:
  - imagedb:image_database
  links:
   - discovery
   - configserver

musicservice:
  image: mateuszsojka/music-service
  container_name: music-service
  external_links:
  - musicdb:music_database
  links:
   - discovery
   - configserver

videoservice:
  image: mateuszsojka/video-service
  container_name: video-service
  external_links:
  - videodb:video_database
  links:
   - discovery
   - configserver