eureka-service:
  image: mateuszsojka/eureka-service
  container_name: eureka-service
  ports:
   - 8761:8761

wait_for_eureka:
  image: dadarek/wait-for-dependencies
  links:
   - eureka-service
  command: eureka-service:8761
  environment:
   - SLEEP_LENGTH=30

config-server:
  image: mateuszsojka/config-server
  container_name: config-server
  restart: always
  ports:
   - 8888:8888
  links:
   - eureka-service:eureka-service

hystrix-dashboard:
  image: mateuszsojka/hystrix-dashboard
  container_name: hystrix-dashboard
  restart: always
  ports:
   - 7979:7979
  links:
   - eureka-service:eureka-service
   - config-server:config-server

auth-service:
  image: mateuszsojka/auth-service
  container_name: auth-service
  restart: always
  ports:
   - 9000:9000
  external_links:
   - usersdb:usersdb
  links:
   - eureka-service:eureka-service
   - config-server:config-server

ebook-service:
  image: mateuszsojka/ebook-service
  container_name: ebook-service
  restart: always
  ports:
  - 9002:9002
  external_links:
  - ebookdb:ebookdb
  links:
   - eureka-service:eureka-service
   - config-server:config-server

image-service:
  image: mateuszsojka/image-service
  container_name: image-service
  restart: always
  ports:
  - 9004:9004
  external_links:
  - imagedb:imagedb
  links:
   - eureka-service:eureka-service
   - config-server:config-server

music-service:
  image: mateuszsojka/music-service
  container_name: music-service
  restart: always
  ports:
  - 9006:9006
  external_links:
  - musicdb:musicdb
  links:
   - eureka-service:eureka-service
   - config-server:config-server

video-service:
  image: mateuszsojka/video-service
  container_name: video-service
  restart: always
  ports:
  - 9008:9008
  external_links:
  - videodb:videodb
  links:
   - eureka-service:eureka-service
   - config-server:config-server

wait_for_services:
  image: dadarek/wait-for-dependencies
  links:
   - auth-service
   - ebook-service
   - image-service
   - music-service
   - video-service
  command: auth-service:9000 ebook-service:9002 image-service:9004 music-service:9006 video-service:9008
  environment:
   - SLEEP_LENGTH=30

api-gateway:
  image: mateuszsojka/api-gateway
  container_name: api-gateway
  restart: always
  ports:
  - 8080:8080
  links:
  - eureka-service:eureka-service
  - config-server:config-server
  - auth-service:auth-service
  - ebook-service:ebook-service
  - image-service:image-service
  - music-service:music-service
  - video-service:video-service