server:
  port: 8761

eureka:
  instance:
    hostname: eureka-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-service:${server.port}/eureka/

spring.cloud.config.discovery.enabled: true