server:
  port: 8888

eureka:
  instance:
    hostname: config-server
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Andrzej997/Streamer-Spring-Cloud-Config-Server